// This file is generated by Rust. Do not edit.

// This file has been generated by Specta. Do not edit this file manually.
export type AiAnchor = {
	id: string,
	repoId: string,
	repoName: string,
	filePath: string,
	staged: boolean,
	oldLine: number | null,
	newLine: number | null,
	fingerprint: string,
};

export type AiApplyResult = {
	commitCount: number,
	commitHashes: string[],
	backupRef: string | null,
	recoveryCommand: string | null,
	completedGroups: number | null,
};

export type AiCandidate = {
	repoId: string,
	paths: string[],
	stagedOnly: boolean,
};

export type AiCommit = {
	repoId: string,
	hash: string,
};

export type AiComposerSource = {
	sessionId: string,
	mode: string,
	repoId: string,
	repoName: string,
	vcsKind: string,
	branch: string,
	sourceLabel: string,
	units: AiUnit[],
	originalCommitCount: number | null,
};

export type AiConfig = {
	executionMode: string,
	provider: string,
	apiProtocol: string,
	apiUrl: string,
	model: string,
	maxInputTokens: number,
	maxOutputTokens: number,
	cliProvider: string,
	cliModel: string,
	cliTimeoutSeconds: number,
	cliExecutablePaths: { [key in string]: string },
};

export type AiEvent = {
	type: string,
	requestId: string,
	phase: string,
	delta: string,
};

export type AiFinding = {
	id: string,
	severity: string,
	title: string,
	anchorId: string,
	evidence: string,
	impact: string,
	suggestion: string,
	anchor: AiAnchor,
};

export type AiGroup = {
	id: string,
	message: string,
	rationale?: string,
	unitIds: string[],
};

export type AiPrompt = {
	text: string,
	source: string,
	path: string | null,
};

export type AiRequest = {
	requestId: string,
	task: AiTask,
	workspaceId: string,
	candidates?: AiCandidate[],
	commits?: AiCommit[],
	userPrompt?: string,
	repoId: string | null,
	path: string | null,
	conflictIndexes?: number[],
	sessionId: string | null,
	unitIds?: string[],
};

export type AiResolution = {
	index: number,
	lines: string[],
};

export type AiResult = {
	text: string,
	provider: string,
	model: string,
	promptSource: string,
	inputTruncated: boolean,
	durationMs: number,
	review: AiReview | null,
	resolutions: AiResolution[],
	groups: AiGroup[],
	fileCount: number,
	repositoryCount: number,
};

export type AiReview = {
	verdict: string,
	summary: string,
	findings: AiFinding[],
};

export type AiRuntime = {
	configured: boolean,
	keySaved: boolean,
	provider: string,
	available: boolean,
	message: string,
	version: string | null,
};

export type AiTask = "commit-message" | "commit-explanation" | "code-review" | "commit-composer" | "merge-conflict";

export type AiUnit = {
	id: string,
	filePath: string,
	oldPath: string | null,
	kind: string,
	status: string,
	title: string,
	diff: string,
	language: string,
	added: number,
	removed: number,
	atomic: boolean,
};

export type AppStateSnapshot = {
	schemaVersion?: number,
	settings?: DesktopSettings,
	layout?: LayoutState,
	lastWorkspaceId: string | null,
	openWorkspaceIds?: string[],
	activeWorkspaceId?: string | null,
	recentWorkspaces: WorkspaceDescriptor[],
	commitSelections?: { [key in string]: RepositoryCommitSelection[] },
	theme?: ThemePreference | null,
	language?: LanguagePreference | null,
	uiFontSize?: UiFontSizePreference | null,
	panelSizes?: PanelSizes | null,
	activeTab?: string | null,
	fileViewMode?: string | null,
	stashViewMode?: string | null,
	externalEditor?: ExternalEditor | null,
	branchSidebarCollapsed?: boolean | null,
	branchSidebarCollapsedSections?: string[] | null,
};

export type BatchCommitTarget = {
	repoId: string,
	message: string,
	amend: boolean,
	paths: string[],
	unstagePaths?: string[],
	noVerify?: boolean,
	stagedOnly?: boolean,
};

export type BootstrapData = {
	state: AppStateSnapshot,
	tools: ToolAvailability,
	capabilities: DesktopCapabilities,
	applicationSessionId: string,
	launchWorkspaceId?: string | null,
	runtime?: RuntimeCapabilities,
};

export type BranchCompareResult = {
	base: string,
	target: string,
	baseCommits: CommitNode[],
	targetCommits: CommitNode[],
	files: CommitFile[],
};

export type BranchInfo = {
	name: string,
	current: boolean,
	remote: boolean,
	remoteName?: string | null,
	upstream: string | null,
	ahead: number,
	behind: number,
	detachedTag?: string | null,
	detachedHash?: string | null,
	lastCommitMessage?: string | null,
	lastCommitDate?: string | null,
};

export type BranchOperation = { type: "create"; name: string; from: string | null; checkout?: boolean | null } | { type: "checkout"; name: string } | { type: "merge"; name: string } | { type: "rebase"; name: string } | { type: "rename"; old_name: string; new_name: string } | { type: "delete"; name: string; force: boolean };

export type BranchOperationResult = {
	completed: boolean,
	conflicted: boolean,
};

export type BranchRecoveryOperation = { type: "stashAndCheckout"; target: string } | { type: "carryChanges"; target: string } | { type: "forceCheckout"; target: string } | { type: "stashAndMerge"; target: string };

export type BranchRecoveryResult = {
	status: BranchRecoveryStatus,
	target: string,
	stashReference: string | null,
	changesRestored: boolean,
	error: DesktopError | null,
	recoveryHint: string | null,
};

export type BranchRecoveryStatus = "completed" | "conflicted" | "partialFailure";

export type BridgeCommand = { type: "bootstrap" } | { type: "runtimeCapabilities" } | { type: "saveAppState"; payload: {
	state: AppStateSnapshot,
} } | { type: "saveCommitSelections"; payload: {
	workspace_id: string,
	selections: RepositoryCommitSelection[],
} } | { type: "updateSettings"; payload: {
	settings: DesktopSettings,
	changed_fields?: string[] | null,
} } | { type: "aiRuntime" } | { type: "aiSaveKey"; payload: {
	provider: string,
	api_url: string,
	key: string | null,
} } | { type: "aiPrompt"; payload: {
	task: AiTask,
	workspace_id: string | null,
	repo_id: string | null,
	scope: string,
	action: string,
	text: string | null,
} } | { type: "aiGenerate"; payload: {
	request: AiRequest,
} } | { type: "aiComposerPrepare"; payload: {
	workspace_id: string,
	repo_id: string,
	paths: string[],
	staged_only: boolean,
	hashes: string[],
} } | { type: "aiComposerApply"; payload: {
	workspace_id: string,
	repo_id: string,
	session_id: string,
	groups: AiGroup[],
	no_verify: boolean,
} } | { type: "aiReviewLocate"; payload: {
	workspace_id: string,
	anchor: AiAnchor,
} } | { type: "aiResetCliSession" } | { type: "updateLayout"; payload: {
	layout: LayoutState,
} } | { type: "workspaceOpen"; payload: {
	paths: string[],
} } | { type: "workspaceRemoveRecent"; payload: {
	workspace_id: string,
} } | { type: "workspaceRefresh"; payload: {
	workspace_id: string,
} } | { type: "initializeRepository"; payload: {
	workspace_id: string,
	target_path: string,
} } | { type: "cloneRepository"; payload: {
	url: string,
	parent_path: string,
	target_name: string,
	provider_account_id: string | null,
} } | { type: "checkoutSvnRepository"; payload: {
	url: string,
	parent_path: string,
	target_name: string,
	username: string | null,
	password: string | null,
} } | { type: "providerAccounts" } | { type: "providerGithubBegin"; payload: {
	account_id: string | null,
} } | { type: "providerGithubComplete"; payload: {
	flow_id: string,
} } | { type: "providerGithubSave"; payload: {
	account_id: string | null,
	token: string,
} } | { type: "providerGitlabSave"; payload: {
	account_id: string | null,
	host: string,
	token: string,
} } | { type: "providerGiteeSave"; payload: {
	account_id: string | null,
	token: string,
} } | { type: "providerRemove"; payload: {
	account_id: string,
} } | { type: "providerRepositories"; payload: {
	account_id: string,
	query: string | null,
	page: number,
	per_page: number,
} } | { type: "providerNamespaces"; payload: {
	account_id: string,
} } | { type: "resolveAuthorAvatar"; payload: {
	workspace_id: string,
	repo_id: string,
	email: string,
	author_name: string,
} } | { type: "publishRepository"; payload: {
	workspace_id: string,
	repo_id: string,
	account_id: string,
	namespace_id: string | null,
	name: string,
	description: string,
	visibility: RemoteVisibility,
	push: boolean,
} } | { type: "windowOpenNew"; payload: {
	paths: string[] | null,
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
	transfer: WindowTabTransfer | null,
} } | { type: "windowStoreTabSession"; payload: {
	transfer: WindowTabTransfer,
	session: unknown,
} } | { type: "windowReadTabSession"; payload: {
	transfer_id: string,
} } | { type: "windowDiscardTabSession"; payload: {
	transfer_id: string,
} } | { type: "windowSyncTabs"; payload: {
	workspace_paths: string[][],
	active_workspace_id: string | null,
} } | { type: "windowFocusWorkspace"; payload: {
	paths: string[],
} } | { type: "windowTabDrop"; payload: {
	transfer: WindowTabTransfer,
	screen_x: number | null,
	screen_y: number | null,
} } | { type: "windowCompleteTabTransfer"; payload: {
	transfer_id: string,
	source_window_label: string,
	tab_id: string,
	target_window_label: string,
	accepted: boolean,
} } | { type: "windowSyncBounds"; payload: {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
} } | { type: "windowSetSize"; payload: {
	width: number | null,
	height: number | null,
	center: boolean,
} } | { type: "repositoryStatus"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "fileDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	staged: boolean,
	revision: string | null,
	from_revision: string | null,
	to_revision: string | null,
} } | { type: "stashFileDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	reference: string,
	relative_path: string,
} } | { type: "shelfFileDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	shelf_id: string,
	relative_path: string,
} } | { type: "stage"; payload: {
	workspace_id: string,
	repo_id: string,
	paths: string[],
	allow_truncated?: boolean,
} } | { type: "unstage"; payload: {
	workspace_id: string,
	repo_id: string,
	paths: string[],
} } | { type: "discard"; payload: {
	workspace_id: string,
	repo_id: string,
	paths: string[],
} } | { type: "deletePaths"; payload: {
	workspace_id: string,
	repo_id: string,
	paths: string[],
} } | { type: "addIgnore"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
} } | { type: "ignoreRules"; payload: {
	workspace_id: string,
	repo_id: string,
	directory: string,
} } | { type: "svnIgnoreEntries"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "updateIgnoreRules"; payload: {
	workspace_id: string,
	repo_id: string,
	directory: string,
	patterns: string[],
} } | { type: "commit"; payload: {
	workspace_id: string,
	repo_id: string,
	message: string,
	amend: boolean,
	paths: string[],
	no_verify?: boolean,
	staged_only?: boolean,
} } | { type: "commitSafetyCheck"; payload: {
	workspace_id: string,
	repo_id: string,
	paths: string[],
	staged_only?: boolean,
} } | { type: "batchCommit"; payload: {
	workspace_id: string,
	targets: BatchCommitTarget[],
	push: boolean,
} } | { type: "recentCommitMessages"; payload: {
	workspace_id: string,
	repo_ids: string[],
	limit: number,
} } | { type: "lastCommitMessage"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "sync"; payload: {
	workspace_id: string,
	repo_id: string,
	action: SyncAction,
	remote: string | null,
	branch: string | null,
	force?: boolean | null,
} } | { type: "history"; payload: {
	workspace_id: string,
	repo_id: string,
	skip: number,
	limit: number,
	query: HistoryQuery,
} } | { type: "historyTopology"; payload: {
	workspace_id: string,
	repo_id: string,
	svn_limit: number,
	limit?: number | null,
	revision: string | null,
} } | { type: "commitDetail"; payload: {
	workspace_id: string,
	repo_id: string,
	revision: string,
} } | { type: "commitMergeCommits"; payload: {
	workspace_id: string,
	repo_id: string,
	revision: string,
	parents: string[],
} } | { type: "commitMergeParentFiles"; payload: {
	workspace_id: string,
	repo_id: string,
	revision: string,
	parent_hash: string,
} } | { type: "unpushedCommits"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "unpushedChanges"; payload: {
	workspace_id: string,
	repo_id: string,
	oldest_revision: string | null,
} } | { type: "incomingCommits"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "incomingChanges"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "unpushedOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: UnpushedOperation,
} } | { type: "historyOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: HistoryOperation,
} } | { type: "createPatch"; payload: {
	workspace_id: string,
	repo_id: string,
	revisions: string[],
} } | { type: "savePatch"; payload: {
	workspace_id: string,
	repo_id: string,
	revisions: string[],
	path: string,
} } | { type: "branches"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "branchOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: BranchOperation,
} } | { type: "branchRecovery"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: BranchRecoveryOperation,
} } | { type: "tags"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "tagOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: TagOperation,
} } | { type: "stashes"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "stashOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: StashOperation,
} } | { type: "systemOpen"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	reveal: boolean,
	external: boolean,
} } | { type: "shelves"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "shelfOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: ShelfOperation,
} } | { type: "changelists"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "changelistOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: ChangelistOperation,
} } | { type: "worktrees"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "worktreeOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: WorktreeOperation,
} } | { type: "openWorktree"; payload: {
	workspace_id: string,
	repo_id: string,
	path: string,
	reveal: boolean,
} } | { type: "worktreeDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	path: string,
	base_ref: string,
} } | { type: "worktreeFileDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	path: string,
	base_ref: string,
	relative_path: string,
} } | { type: "branchWorkingDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	base_ref: string,
} } | { type: "branchWorkingFileDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	base_ref: string,
	relative_path: string,
} } | { type: "subtrees"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "subtreeStatuses"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "subtreeOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: SubtreeOperation,
} } | { type: "submodules"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "submoduleOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: SubmoduleOperation,
} } | { type: "branchCompare"; payload: {
	workspace_id: string,
	repo_id: string,
	base: string,
	target: string,
} } | { type: "branchCompareCommits"; payload: {
	workspace_id: string,
	repo_id: string,
	base: string,
	target: string,
	side: string,
	skip: number,
	limit: number,
	query: HistoryQuery,
} } | { type: "remotes"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "remoteOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: RemoteOperation,
} } | { type: "conflicts"; payload: {
	workspace_id: string,
	repo_id: string | null,
} } | { type: "conflictVersions"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
} } | { type: "conflictSave"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	content: string,
	expected_fingerprint: string,
	delete_file?: boolean | null,
} } | { type: "conflictAccept"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	choice: ConflictChoice,
} } | { type: "abortRepositoryOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: string,
} } | { type: "continueRepositoryOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: string,
	skip?: boolean | null,
} } | { type: "gitUnlockIndex"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "restoreConflicts"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "gitIdentity"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "gitProfileOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: GitProfileOperation,
} } | { type: "svnAccount"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "svnAccountOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: SvnAccountOperation,
} } | { type: "svnOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: SvnOperation,
} } | { type: "diffLineHistoryTarget"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	source_revision: string,
	line_range: LineRange,
} } | { type: "fileHistory"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	cursor: string | null,
	limit: number,
} } | { type: "fileRevisionContent"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	revision: string,
} } | { type: "logGet"; payload: {
	channel: LogChannel | null,
	level: LogLevel | null,
	limit: number | null,
} } | { type: "logClear" } | { type: "logFormat"; payload: {
	entries: LogEntry[],
} } | { type: "logStorageStatus" } | { type: "logOpenFolder" } | { type: "logExport"; payload: {
	target_path: string,
	entries?: LogEntry[] | null,
} } | { type: "logClientPush"; payload: {
	level: LogLevel,
	channel: LogChannel,
	message: string,
	details: string | null,
} };

export type CapabilityStatus = {
	available: boolean,
	reasonCode: string | null,
	detail: string | null,
};

export type CatFileFilterMode = "filters" | "textconv" | "none";

export type ChangelistEntry = {
	id: string,
	name: string,
	files: string[],
	isDefault?: boolean,
	isActive?: boolean,
};

export type ChangelistOperation = { type: "create"; name: string } | { type: "rename"; changelist_id: string; name: string } | { type: "delete"; changelist_id: string } | { type: "assign"; changelist_id: string | null; paths: string[] } | { type: "setActive"; changelist_id: string };

export type ChangesDisplayMode = "simplified" | "changelists" | "vscode";

export type CheckoutRepositoryResult = {
	path: string,
};

export type CleanWorkingTreeMethod = "shelve" | "stash";

export type CloneRepositoryResult = {
	path: string,
};

export type CommitBranches = {
	local: string[],
	remote: string[],
	tags: string[],
	isHead?: boolean | null,
};

export type CommitDetail = {
	commit: CommitNode,
	fullMessage: string,
	files: CommitFile[],
	branches: CommitBranches,
	mergeParentChanges?: MergeParentChange[],
};

export type CommitFile = {
	path: string,
	status: string,
	added: number | null,
	removed: number | null,
};

export type CommitNode = {
	repoId: string,
	hash: string,
	shortHash: string,
	parents: string[],
	author: string,
	email: string,
	authorDate: string,
	committerDate: string,
	message: string,
	refs: string[],
	incoming?: boolean,
	unpushed?: boolean,
};

export type CommitPathOperationEntry = {
	revision: string,
	path: string,
	status: string,
};

export type CommitSafetyCheckResult = {
	hasIssues: boolean,
	sensitiveFiles: string[],
	largeFiles: LargeFileInfo[],
	invalidFileNames: InvalidFileNameInfo[],
	crlfFiles: string[],
};

export type ConflictBlock = {
	index: number,
	oursLabel: string,
	theirsLabel: string,
	oursLines: string[],
	baseLines: string[],
	theirsLines: string[],
	startLine: number,
	endLine: number,
};

export type ConflictChoice = "mine" | "theirs" | "working";

export type ConflictFile = {
	repoId: string,
	repoName: string,
	repoColor: string,
	path: string,
	kind: VcsKind,
	binary: boolean,
	conflictType?: string,
	conflictTypes?: string[] | null,
	actions?: string[],
	currentStatus?: string | null,
	incomingStatus?: string | null,
};

export type ConflictResolutionResult = {
	resolved: boolean,
	autoCommitError: string | null,
	autoCommitted?: boolean,
};

export type DefaultCommitAction = "commit" | "commitAndPush";

export type DefaultSaveAction = "stash" | "shelf";

export type DesktopCapabilities = {
	ai: boolean,
	initializeRepository?: boolean,
	cloneRepository?: boolean,
	stash: boolean,
	shelf: boolean,
	changelist: boolean,
	worktree: boolean,
	subtree: boolean,
	submodule?: boolean,
	compare: boolean,
	remoteManagement: boolean,
	identity?: boolean,
	svnAccount?: boolean,
	fileHistory?: boolean,
	secureCredentials?: boolean,
	systemNotifications?: boolean,
	availability?: { [key in string]: CapabilityStatus },
};

export type DesktopError = {
	code: string,
	message: string,
	command: string | null,
	exitCode: number | null,
	stderr: string | null,
	recoverable: boolean,
	operation?: string | null,
	workspaceId?: string | null,
	repositoryId?: string | null,
	subject?: string | null,
	hint?: string | null,
	restoreWarning?: UpdateRestoreWarning | null,
};

export type DesktopSettings = {
	aiConfig?: AiConfig,
	theme: ThemePreference,
	language: LanguagePreference,
	uiFontSize: UiFontSizePreference,
	layoutDensity?: LayoutDensity,
	changesDisplayMode: ChangesDisplayMode,
	defaultCommitAction: DefaultCommitAction,
	defaultSaveAction: DefaultSaveAction,
	promptBeforeAddingUntracked: boolean,
	suppressDivergedWarning: boolean,
	autoRefreshInterval: number,
	fetchOnStartup: boolean,
	autoFetchOnFocus?: boolean,
	resetViewLocationsOnStartup: boolean,
	notifyIncomingCommits: boolean,
	notifyUnpushedCommits: boolean,
	repositoryScanDepth: number,
	ignoredFolders: string[],
	maximumGraphCommits: number,
	projectColors: { [key in string]: string },
	hiddenRepositoryIds?: string[],
	externalEditor: ExternalEditor | null,
	autoCheckUpdates?: boolean,
	skippedUpdateVersion?: string | null,
	onlineAvatarsEnabled?: boolean,
	gravatarEnabled?: boolean,
	avatarCrossPlatformFallback?: boolean,
	fileIconTheme?: FileIconThemePreference,
	noVerify?: boolean,
	autoCommitResolvedMerge?: boolean,
	warnOnLargeFiles?: boolean,
	largeFileSizeLimitMb?: number,
	warnOnDetachedHead?: boolean,
	warnOnCrlf?: boolean,
	warnOnInvalidFileNames?: boolean,
	protectedBranches?: string[],
	syncProtectedBranchesFromGithub?: boolean,
	showPushDialogForProtectedBranches?: boolean,
	onPushRejected?: OnPushRejectedAction,
	branchCleanCharacter?: string,
	cherryPickAddSuffix?: boolean,
	useSafeForcePush?: boolean,
	updateProjectMethod?: UpdateProjectMethod,
	updateProjectCleanWorkingTree?: CleanWorkingTreeMethod,
	updateProjectShowNotification?: boolean,
	cloneRecursiveSubmodules?: boolean,
	shelveComparisonBase?: ShelveComparisonBase,
	catFileFilterMode?: CatFileFilterMode,
	fetchTags?: FetchTagsMode,
	excludeIgnoredDirectories?: boolean,
};

export type DiffDocument = {
	path: string,
	content: string,
	language: string,
	binary: boolean,
	truncated: boolean,
	lineCount: number,
};

export type DiffLineHistoryTarget = {
	path: string,
	revision: string,
	lineRange: LineRange,
};

export type EffectiveGitIdentity = {
	userName: string,
	email: string,
	source: GitIdentitySource,
	profileId: string | null,
	valid: boolean,
};

export type ExternalEditor = {
	executable: string,
	args: string[],
};

export type FetchTagsMode = "auto" | "all" | "none";

export type FileChange = {
	path: string,
	status: string,
	staged: boolean,
	unstaged: boolean,
	conflicted: boolean,
	conflictType?: string | null,
	conflictTypes?: string[] | null,
	conflictStatus?: string | null,
	submodule?: boolean,
	isTruncated?: boolean,
	truncationReason?: string | null,
};

export type FileHistoryEntry = {
	revision: string,
	previousRevision: string | null,
	path: string,
	previousPath: string | null,
	author: string,
	date: string,
	message: string,
	status: string,
};

export type FileHistoryPage = {
	entries: FileHistoryEntry[],
	nextCursor: string | null,
};

export type FileIconThemePreference = "material" | "catppuccin" | "seti" | "codicon";

export type FileRevisionDocument = {
	revision: string,
	path: string,
	content: string,
	binary: boolean,
	truncated: boolean,
};

export type GitIdentitySource = "custom" | "local" | "global" | "missing";

export type GitIdentityState = {
	profiles: GitProfile[],
	selectedProfileId: string | null,
	local: EffectiveGitIdentity | null,
	global: EffectiveGitIdentity | null,
	effective: EffectiveGitIdentity,
};

export type GitProfile = {
	id: string,
	label: string,
	userName: string,
	email: string,
};

export type GitProfileOperation = { type: "save"; profile: GitProfile } | { type: "delete"; profile_id: string } | { type: "select"; profile_id: string | null };

export type GithubDeviceFlow = {
	flowId: string,
	userCode: string,
	verificationUri: string,
	expiresAt: string,
	interval: number,
};

export type GraphCommitNode = {
	repoId: string,
	hash: string,
	parents: string[],
	committerDate: string,
	refs: string[],
};

export type HistoryOperation = { type: "checkout"; revision: string } | { type: "cherryPick"; revision: string } | { type: "revert"; revisions: string[] } | { type: "reset"; revision: string; mode: string; expectedBranch?: string | null; expectedHead?: string | null } | { type: "checkoutFile"; revision: string; path: string } | { type: "revertFile"; revision: string; path: string } | { type: "applyPaths"; entries: CommitPathOperationEntry[] } | { type: "revertPaths"; entries: CommitPathOperationEntry[] } | { type: "svnUpdateTo"; revision: string };

export type HistoryPage = {
	commits: CommitNode[],
	hasMore: boolean,
};

export type HistoryQuery = {
	text: string | null,
	author: string | null,
	fromDate: string | null,
	toDate: string | null,
	path: string | null,
	revision: string | null,
	lineRange?: LineRange | null,
};

export type IgnoreRules = {
	directory: string,
	source: string,
	patterns: string[],
};

export type IncomingCommit = {
	hash: string,
	shortHash: string,
	message: string,
	body?: string | null,
	fullMessage?: string | null,
	author: string,
	authorEmail?: string | null,
	date: string,
	filesChanged: number,
	additions: number,
	deletions: number,
	parents: string[],
	potentialConflictPaths: string[],
};

export type InitializeRepositoryResult = {
	snapshot: WorkspaceSnapshot,
	repositoryId: string,
};

export type InvalidFileNameInfo = {
	path: string,
	reason: string,
};

export type LanguagePreference = "system" | "zhCn" | "en";

export type LargeFileInfo = {
	path: string,
	sizeBytes: number | null,
	sizeFormatted: string,
};

export type LayoutDensity = "comfortable" | "compact";

export type LayoutState = {
	panelSizes: PanelSizes,
	activeTab: string,
	fileViewMode: string,
	stashViewMode: string,
	branchSidebarCollapsed: boolean,
	branchSidebarCollapsedSections: string[],
};

export type LineRange = {
	start: number,
	end: number,
};

export type LogChannel = "git" | "svn" | "core" | "ui";

export type LogContext = {
	workspaceId: string | null,
	repositoryId: string | null,
	operationId: string | null,
	workspaceName: string | null,
	repositoryName: string | null,
};

export type LogEntry = {
	id: string,
	timestamp: string,
	level: LogLevel,
	channel: LogChannel,
	message: string,
	details: string | null,
	durationMs: number | null,
	exitCode: number | null,
	cwd: string | null,
	context?: LogContext | null,
};

export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";

export type MergeCommitSummary = {
	hash: string,
	shortHash: string,
	message: string,
	author: string,
	authorDate: string,
	parentIndex: number,
};

export type MergeParentChange = {
	hash: string,
	shortHash: string,
	message: string,
	authorName: string,
	authorDate: string,
	parentIndex: number,
	fileCount: number,
};

export type MergeVersions = {
	path: string,
	base: string,
	ours: string,
	theirs: string,
	working: string,
	markerContent: string,
	conflicts: ConflictBlock[],
	oursLabel: string,
	theirsLabel: string,
	language: string,
	fingerprint: string,
	binary: boolean,
	oursStatus?: string | null,
	theirsStatus?: string | null,
};

export type NotificationPermissionState = "notRequested" | "allowed" | "denied" | "restricted" | "unavailable";

export type OnPushRejectedAction = "prompt" | "rebaseAndRetry" | "error";

export type OperationDomain = "application" | "workspace" | "status" | "diff" | "history" | "branch" | "tag" | "commit" | "sync" | "conflict" | "stash" | "shelf" | "changelist" | "worktree" | "subtree" | "submodule" | "remote" | "identity" | "svnAccount" | "fileHistory" | "system";

export type OperationEvent = {
	operationId: string,
	context: RequestContext,
	status: OperationStatus,
	phase: string,
	message: string,
	startedAt: string,
	cancellable: boolean,
	completed: number | null,
	total: number | null,
	result?: OperationResultSummary | null,
	error: DesktopError | null,
};

export type OperationResultSummary = {
	summary: string,
	succeeded: number,
	failed: number,
};

export type OperationStatus = "queued" | "running" | "succeeded" | "partial" | "failed" | "cancelled" | "timedOut";

export type OperationVisibility = "foreground" | "background";

export type PanelSizes = {
	commit: number,
	branches: number,
	detail: number,
};

export type PatchDocument = {
	fileName: string,
	content: string,
};

export type PublishRepositoryResult = {
	repository: RemoteRepository,
	remoteCreated: boolean,
	remoteConfigured: boolean,
	pushAttempted: boolean,
	pushed: boolean,
	failedStage: string | null,
	recoveryHint: string | null,
	error: DesktopError | null,
};

export type RecentCommitMessage = {
	repoId: string,
	revision: string,
	committedAt: string,
	message: string,
};

export type RefreshScope = "workspaceSnapshot" | "status" | "diff" | "index" | "refs" | "history" | "operation" | "conflicts" | "svnRevision" | "unpushed" | "worktrees" | "subtrees" | "submodules";

export type RemoteInfo = {
	name: string,
	fetchUrl: string,
	pushUrl: string,
};

export type RemoteNamespace = {
	id: string,
	name: string,
	fullPath: string,
	kind: string,
	host: string,
};

export type RemoteOperation = { type: "add"; name: string; url: string } | { type: "rename"; old_name: string; new_name: string } | { type: "setUrl"; name: string; url: string; push: boolean } | { type: "remove"; name: string } | { type: "prune"; name: string };

export type RemoteProviderAccount = {
	id: string,
	provider: RemoteProviderKind,
	host: string,
	login: string,
	displayName: string | null,
	secureStorageRef: string,
};

export type RemoteProviderKind = "github" | "gitlab" | "gitee";

export type RemoteRepository = {
	id: string,
	provider: RemoteProviderKind,
	host: string,
	name: string,
	fullName: string,
	cloneUrl: string,
	webUrl: string | null,
	defaultBranch: string | null,
	namespace: RemoteNamespace | null,
	private: boolean,
};

export type RemoteRepositoryPage = {
	items: RemoteRepository[],
	page: number,
	hasMore: boolean,
};

export type RemoteVisibility = "private" | "internal" | "public";

export type RepositoryCapabilities = {
	status: boolean,
	diff: boolean,
	commit: boolean,
	sync: boolean,
	history: boolean,
	conflict: boolean,
	stash: boolean,
	shelf: boolean,
	changelist: boolean,
	worktree: boolean,
	subtree: boolean,
	submodule: boolean,
	compare: boolean,
	remoteManagement: boolean,
	identity: boolean,
	svnAccount: boolean,
	fileHistory: boolean,
	availability?: { [key in string]: CapabilityStatus },
};

export type RepositoryCommitSelection = {
	repoId: string,
	paths: string[],
};

export type RepositoryEvent = {
	workspaceId: string,
	repoId: string | null,
	generation: number,
	source: RepositoryEventSource,
	scopes: RefreshScope[],
};

export type RepositoryEventSource = "watcher" | "operation" | "scheduler" | "otherWindow";

export type RepositoryMeta = {
	id: string,
	name: string,
	rootPath: string,
	color: string,
	kind: VcsKind,
	parentRepoId: string | null,
	depth: number,
	isSubmodule: boolean,
	isWorktree: boolean,
};

export type RepositoryOperationResult = {
	repoId: string,
	commitAttempted: boolean,
	committed: boolean,
	revision: string | null,
	pushAttempted: boolean,
	pushed: boolean,
	failedStage: string | null,
	recoveryHint: string | null,
	error: DesktopError | null,
};

export type RepositoryStatus = {
	meta: RepositoryMeta,
	branch: string,
	revision: string,
	ahead: number,
	behind: number,
	files: FileChange[],
	conflicts: number,
	operation: string | null,
	capabilities?: RepositoryCapabilities,
	toolAvailable?: boolean,
};

export type RepositoryUpdateResult = {
	repoId: string,
	beforeRevision: string,
	afterRevision: string,
	summary: UpdateSummary | null,
	summaryError: DesktopError | null,
	beforeStatus: string,
	afterStatus: string,
};

export type RequestContext = {
	generation: number,
	domain: OperationDomain,
	visibility?: OperationVisibility,
	workspaceId: string | null,
	repositoryId: string | null,
	target: string | null,
};

export type RequestEnvelope = {
	requestId: string,
	context: RequestContext,
	command: BridgeCommand,
};

export type ResponseEnvelope = {
	requestId: string,
	result: unknown,
	error: DesktopError | null,
};

export type RestoreConflictFailure = {
	path: string,
	error: DesktopError,
};

export type RestoreConflictsResult = {
	restoredPaths: string[],
	failures: RestoreConflictFailure[],
};

export type RevisionChanges = {
	fromRevision: string,
	toRevision: string,
	files: CommitFile[],
};

export type RuntimeCapabilities = {
	systemNotifications: CapabilityStatus,
	notificationPermission: NotificationPermissionState,
	secureCredentials: SecureCredentialCapability,
};

export type SecureCredentialCapability = {
	status: CapabilityStatus,
	backend: string | null,
	passwordStdinSupported: boolean,
};

export type SettingsEffects = {
	rescanWorkspace: boolean,
	reloadHistory: boolean,
	restartAutoRefresh: boolean,
};

export type SettingsUpdateResult = {
	settings: DesktopSettings,
	effects: SettingsEffects,
};

export type ShelfEntry = {
	id: string,
	name: string,
	createdAt: string,
	branch?: string | null,
	files: ShelfFileEntry[],
};

export type ShelfFileEntry = {
	path: string,
	status: string,
};

export type ShelfOperation = { type: "create"; name: string; paths: string[] } | { type: "apply"; shelf_id: string; paths?: string[] | null } | { type: "drop"; shelf_id: string };

export type ShelveComparisonBase = "local" | "parent";

export type StashEntry = {
	reference: string,
	hash: string,
	branch: string,
	message: string,
	fullMessage: string,
	date: string,
	files: ShelfFileEntry[],
};

export type StashOperation = { type: "create"; message: string; paths: string[]; include_untracked: boolean } | { type: "apply"; reference: string; expected_hash?: string | null } | { type: "pop"; reference: string; expected_hash?: string | null } | { type: "drop"; reference: string; expected_hash?: string | null };

export type SubmoduleConflictStages = {
	base: string | null,
	ours: string | null,
	theirs: string | null,
};

export type SubmoduleEntry = {
	name: string,
	path: string,
	url: string,
	initialized: boolean,
	revision: string | null,
	branch: string | null,
	dirty: boolean,
	syncStatus: SubmoduleSyncStatus,
	recordedCommit: string | null,
	indexCommit?: string | null,
	conflictStages?: SubmoduleConflictStages | null,
	currentBranch: string | null,
	detached: boolean,
	unpushedCount: number,
	typeChange?: boolean,
	companionPath?: string | null,
	diffSummary?: string | null,
};

export type SubmoduleOperation = { type: "add"; url: string; path: string; branch: string | null; allow_file_protocol: boolean } | { type: "init"; path: string; recursive: boolean } | { type: "update"; path: string; init: boolean; recursive: boolean; remote: boolean } | { type: "deinit"; path: string; force: boolean } | { type: "sync"; path: string; recursive: boolean } | { type: "updateAll"; init: boolean; recursive: boolean; remote: boolean } | { type: "remove"; path: string; force: boolean } | { type: "resolveConflict"; path: string; choice: ConflictChoice } | { type: "push"; path: string } | { type: "pull"; path: string; rebase: boolean };

export type SubmoduleSyncStatus = "synced" | "outOfSync" | "uninitialized" | "conflict";

export type SubtreeEntry = {
	id: string,
	prefix: string,
	remote: string,
	branch: string,
	squash: boolean,
	state: SubtreeState,
};

export type SubtreeOperation = { type: "add"; prefix: string; remote: string; branch: string; squash: boolean } | { type: "pull"; subtree_id: string } | { type: "push"; subtree_id: string } | { type: "register"; prefix: string; remote: string; branch: string; squash: boolean } | { type: "edit"; subtree_id: string; prefix: string; remote: string; branch: string; squash: boolean } | { type: "deleteRegistry"; subtree_id: string } | { type: "removeFiles"; subtree_id: string } | { type: "split"; subtree_id: string; branch: string | null } | { type: "merge"; subtree_id: string; revision: string; squash: boolean; message: string | null };

export type SubtreePushStatus = {
	subtreeId: string,
	aheadCount: number | null,
	hasUpdates: boolean,
	remoteRef: string | null,
	splitHash: string | null,
	remoteHash: string | null,
	error: string | null,
};

export type SubtreeState = "active" | "pending";

export type SvnAccountOperation = { type: "switch"; username: string; password: string; remember: boolean } | { type: "save"; username: string; password: string | null } | { type: "delete" } | { type: "test" } | { type: "clearNative"; credential_id: string };

export type SvnAccountState = {
	repositoryUrl: string,
	repositoryRoot: string,
	username: string | null,
	passwordStored: boolean,
	secureStorageAvailable: boolean,
	passwordStdinSupported: boolean,
	connectionOk: boolean | null,
	source?: SvnCredentialSource,
	nativeCredentials?: SvnNativeCredential[],
};

export type SvnCredentialSource = "versionDockSecureStore" | "nativeCache" | "session" | "none";

export type SvnNativeCredential = {
	id: string,
	realm: string,
	username: string | null,
};

export type SvnOperation = { type: "removeIgnoreEntries"; entries: IgnoreRules[] } | { type: "cleanup"; break_locks: boolean; remove_unversioned: boolean; remove_ignored: boolean; include_externals: boolean } | { type: "resolveWorking"; paths: string[] } | { type: "lock"; paths: string[]; message: string | null; force: boolean } | { type: "unlock"; paths: string[]; force: boolean } | { type: "relocate"; from_url: string; to_url: string } | { type: "switch"; url: string; revision: string | null; ignore_ancestry: boolean } | { type: "copy"; source_url: string; destination_url: string; revision: string | null; message: string };

export type SyncAction = "fetch" | "pull" | "pullRebase" | "pullFfOnly" | "push" | "pushTags" | "update";

export type SyncResult = {
	output: string,
	update: RepositoryUpdateResult | null,
	restoreWarning?: UpdateRestoreWarning | null,
};

export type TagInfo = {
	name: string,
	hash: string,
	date: string,
};

export type TagOperation = { type: "create"; name: string; revision: string | null } | { type: "delete"; name: string; remote: string | null } | { type: "checkout"; name: string } | { type: "merge"; name: string } | { type: "push"; name: string; remote: string };

export type ThemePreference = "system" | "dark2026" | "light2026" | "githubDarkDimmed" | "oneDarkPro" | "dracula" | "nord" | "light" | "dark";

export type ToolAvailability = {
	git: boolean,
	svn: boolean,
	svnadmin: boolean,
	gitVersion?: string | null,
	svnVersion?: string | null,
};

export type UiFontSizePreference = "minimum" | "small" | "standard" | "large" | "maximum";

export type UnpushedCommit = {
	hash: string,
	shortHash: string,
	message: string,
	body?: string | null,
	fullMessage?: string | null,
	author: string,
	authorEmail?: string | null,
	date: string,
	filesChanged: number,
	additions: number,
	deletions: number,
	parents?: string[],
};

export type UnpushedOperation = { type: "revert"; hashes: string[] } | { type: "undoHead"; expectedHash?: string | null } | { type: "drop"; hashes: string[] } | { type: "squash"; hashes: string[]; message: string } | { type: "editMessage"; hash: string; message: string };

export type UpdateDetail = {
	commits: CommitNode[],
	files: CommitFile[],
};

export type UpdateKind = "noChanges" | "fastForward" | "updated";

export type UpdateProjectMethod = "rebase" | "merge" | "prompt";

export type UpdateRestoreWarning = {
	shelf: boolean,
	backupName: string,
	backupId: string,
	conflicted: boolean,
	details: string,
};

export type UpdateSummary = {
	kind: UpdateKind,
	commitCount: number,
	fileCount: number,
	containsMerge: boolean,
	detail: UpdateDetail,
};

export type VcsKind = "git" | "svn";

export type WindowTabImport = {
	transfer: WindowTabTransfer,
	screenX: number | null,
	screenY: number | null,
	targetClientX: number | null,
};

export type WindowTabTransfer = {
	transferId: string,
	sourceWindowLabel: string,
	tabId: string,
	tabName: string,
	paths: string[],
};

export type WindowTabTransferCompleted = {
	transferId: string,
	sourceWindowLabel: string,
	tabId: string,
	targetWindowLabel: string,
	accepted: boolean,
};

export type WorkspaceDescriptor = {
	id: string,
	name: string,
	paths: string[],
	lastOpenedAt: string,
	available: boolean,
};

export type WorkspaceEvent = {
	workspaceId: string,
	generation: number,
	reason: string,
};

export type WorkspaceSnapshot = {
	workspace: WorkspaceDescriptor,
	repositories: RepositoryStatus[],
	generation: number,
	tools: ToolAvailability,
};

export type WorktreeDiffResult = {
	path: string,
	baseRef: string,
	currentRef: string,
	files: CommitFile[],
};

export type WorktreeEntry = {
	path: string,
	head: string,
	branch: string,
	bare: boolean,
	detached: boolean,
	locked: boolean,
	lockReason: string | null,
	prunable: boolean,
	main: boolean,
};

export type WorktreeOperation = { type: "create"; branch: string; new_branch: boolean } | { type: "remove"; path: string; force: boolean } | { type: "lock"; path: string } | { type: "unlock"; path: string } | { type: "prune" };
