// This file is generated by Rust. Do not edit.

// This file has been generated by Specta. Do not edit this file manually.
export type AppStateSnapshot = {
	theme: ThemePreference,
	language: LanguagePreference,
	lastWorkspaceId: string | null,
	recentWorkspaces: WorkspaceDescriptor[],
	panelSizes: PanelSizes,
	activeTab: string,
	fileViewMode: string,
	externalEditor: ExternalEditor | null,
	branchSidebarCollapsed?: boolean,
	branchSidebarCollapsedSections?: string[],
};

export type BootstrapData = {
	state: AppStateSnapshot,
	tools: ToolAvailability,
	capabilities: DesktopCapabilities,
};

export type BranchCompareResult = {
	base: string,
	target: string,
	baseCommits: CommitNode[],
	targetCommits: CommitNode[],
	files: CommitFile[],
};

export type BranchInfo = {
	name: string,
	current: boolean,
	remote: boolean,
	remoteName?: string | null,
	upstream: string | null,
	ahead: number,
	behind: number,
	detachedTag?: string | null,
	detachedHash?: string | null,
};

export type BranchOperation = { type: "create"; name: string; from: string | null } | { type: "checkout"; name: string } | { type: "rename"; old_name: string; new_name: string } | { type: "delete"; name: string; force: boolean };

export type BridgeCommand = { type: "bootstrap" } | { type: "saveAppState"; payload: {
	state: AppStateSnapshot,
} } | { type: "workspaceOpen"; payload: {
	paths: string[],
} } | { type: "workspaceRemoveRecent"; payload: {
	workspace_id: string,
} } | { type: "workspaceRefresh"; payload: {
	workspace_id: string,
} } | { type: "repositoryStatus"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "fileDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	staged: boolean,
	revision: string | null,
	from_revision: string | null,
	to_revision: string | null,
} } | { type: "stage"; payload: {
	workspace_id: string,
	repo_id: string,
	paths: string[],
} } | { type: "unstage"; payload: {
	workspace_id: string,
	repo_id: string,
	paths: string[],
} } | { type: "discard"; payload: {
	workspace_id: string,
	repo_id: string,
	paths: string[],
} } | { type: "commit"; payload: {
	workspace_id: string,
	repo_id: string,
	message: string,
	amend: boolean,
	paths: string[],
} } | { type: "sync"; payload: {
	workspace_id: string,
	repo_id: string,
	action: SyncAction,
	remote: string | null,
} } | { type: "history"; payload: {
	workspace_id: string,
	repo_id: string,
	skip: number,
	limit: number,
	filter: string | null,
} } | { type: "commitDetail"; payload: {
	workspace_id: string,
	repo_id: string,
	revision: string,
} } | { type: "commitMergeCommits"; payload: {
	workspace_id: string,
	repo_id: string,
	revision: string,
	parents: string[],
} } | { type: "unpushedCommits"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "branches"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "branchOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: BranchOperation,
} } | { type: "tags"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "tagOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: TagOperation,
} } | { type: "stashes"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "stashOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: StashOperation,
} } | { type: "systemOpen"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	reveal: boolean,
	external: boolean,
} } | { type: "shelves"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "shelfOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: ShelfOperation,
} } | { type: "changelists"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "changelistOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: ChangelistOperation,
} } | { type: "worktrees"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "worktreeOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: WorktreeOperation,
} } | { type: "subtrees"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "subtreeOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: SubtreeOperation,
} } | { type: "branchCompare"; payload: {
	workspace_id: string,
	repo_id: string,
	base: string,
	target: string,
} } | { type: "remotes"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "remoteOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: RemoteOperation,
} } | { type: "conflicts"; payload: {
	workspace_id: string,
} } | { type: "conflictVersions"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
} } | { type: "conflictSave"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	content: string,
	expected_fingerprint: string,
} } | { type: "conflictAccept"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	choice: ConflictChoice,
} };

export type ChangelistEntry = {
	id: string,
	name: string,
	files: string[],
};

export type ChangelistOperation = { type: "create"; name: string } | { type: "rename"; changelist_id: string; name: string } | { type: "delete"; changelist_id: string } | { type: "assign"; changelist_id: string | null; paths: string[] };

export type CommitBranches = {
	local: string[],
	remote: string[],
	tags: string[],
};

export type CommitDetail = {
	commit: CommitNode,
	fullMessage: string,
	files: CommitFile[],
	branches: CommitBranches,
};

export type CommitFile = {
	path: string,
	status: string,
	added: number | null,
	removed: number | null,
};

export type CommitNode = {
	repoId: string,
	hash: string,
	shortHash: string,
	parents: string[],
	author: string,
	email: string,
	authorDate: string,
	committerDate: string,
	message: string,
	refs: string[],
};

export type ConflictChoice = "mine" | "theirs" | "working";

export type ConflictFile = {
	repoId: string,
	repoName: string,
	repoColor: string,
	path: string,
	kind: VcsKind,
	binary: boolean,
};

export type DesktopCapabilities = {
	ai: boolean,
	stash: boolean,
	shelf: boolean,
	changelist: boolean,
	worktree: boolean,
	subtree: boolean,
	compare: boolean,
	remoteManagement: boolean,
};

export type DesktopError = {
	code: string,
	message: string,
	command: string | null,
	exitCode: number | null,
	stderr: string | null,
	recoverable: boolean,
};

export type DiffDocument = {
	path: string,
	content: string,
	language: string,
	binary: boolean,
	truncated: boolean,
	lineCount: number,
};

export type ExternalEditor = {
	executable: string,
	args: string[],
};

export type FileChange = {
	path: string,
	status: string,
	staged: boolean,
	unstaged: boolean,
	conflicted: boolean,
};

export type HistoryPage = {
	commits: CommitNode[],
	hasMore: boolean,
};

export type LanguagePreference = "system" | "zhCn" | "en";

export type MergeCommitSummary = {
	hash: string,
	shortHash: string,
	message: string,
	author: string,
	authorDate: string,
	parentIndex: number,
};

export type MergeVersions = {
	path: string,
	base: string,
	ours: string,
	theirs: string,
	working: string,
	language: string,
	fingerprint: string,
	binary: boolean,
};

export type PanelSizes = {
	commit: number,
	branches: number,
	detail: number,
};

export type ProgressEvent = {
	requestId: string,
	phase: string,
	message: string,
	completed: number | null,
	total: number | null,
};

export type RemoteInfo = {
	name: string,
	fetchUrl: string,
	pushUrl: string,
};

export type RemoteOperation = { type: "add"; name: string; url: string } | { type: "rename"; old_name: string; new_name: string } | { type: "setUrl"; name: string; url: string; push: boolean } | { type: "remove"; name: string } | { type: "prune"; name: string };

export type RepositoryEvent = {
	workspaceId: string,
	repoId: string,
	generation: number,
	reason: string,
};

export type RepositoryMeta = {
	id: string,
	name: string,
	rootPath: string,
	color: string,
	kind: VcsKind,
	parentRepoId: string | null,
	depth: number,
	isSubmodule: boolean,
	isWorktree: boolean,
};

export type RepositoryStatus = {
	meta: RepositoryMeta,
	branch: string,
	revision: string,
	ahead: number,
	behind: number,
	files: FileChange[],
	conflicts: number,
	operation: string | null,
};

export type RequestEnvelope = {
	requestId: string,
	command: BridgeCommand,
};

export type ResponseEnvelope = {
	requestId: string,
	result: unknown,
	error: DesktopError | null,
};

export type ShelfEntry = {
	id: string,
	name: string,
	createdAt: string,
	files: string[],
};

export type ShelfOperation = { type: "create"; name: string; paths: string[] } | { type: "apply"; shelf_id: string } | { type: "drop"; shelf_id: string };

export type StashEntry = {
	reference: string,
	hash: string,
	branch: string,
	message: string,
	date: string,
};

export type StashOperation = { type: "create"; message: string; paths: string[]; include_untracked: boolean } | { type: "apply"; reference: string } | { type: "pop"; reference: string } | { type: "drop"; reference: string };

export type SubtreeEntry = {
	id: string,
	prefix: string,
	remote: string,
	branch: string,
	squash: boolean,
	state: SubtreeState,
};

export type SubtreeOperation = { type: "add"; prefix: string; remote: string; branch: string; squash: boolean } | { type: "pull"; subtree_id: string } | { type: "push"; subtree_id: string } | { type: "remove"; subtree_id: string };

export type SubtreeState = "active" | "pending";

export type SyncAction = "fetch" | "pull" | "push" | "update";

export type TagInfo = {
	name: string,
	hash: string,
	date: string,
};

export type TagOperation = { type: "create"; name: string; revision: string | null } | { type: "delete"; name: string } | { type: "checkout"; name: string } | { type: "push"; name: string; remote: string };

export type ThemePreference = "system" | "light" | "dark";

export type ToolAvailability = {
	git: boolean,
	svn: boolean,
	svnadmin: boolean,
};

export type UnpushedCommit = {
	hash: string,
	shortHash: string,
	message: string,
	author: string,
	date: string,
	filesChanged: number,
	additions: number,
	deletions: number,
};

export type VcsKind = "git" | "svn";

export type WorkspaceDescriptor = {
	id: string,
	name: string,
	paths: string[],
	lastOpenedAt: string,
	available: boolean,
};

export type WorkspaceEvent = {
	workspaceId: string,
	generation: number,
	reason: string,
};

export type WorkspaceSnapshot = {
	workspace: WorkspaceDescriptor,
	repositories: RepositoryStatus[],
	generation: number,
	tools: ToolAvailability,
};

export type WorktreeEntry = {
	path: string,
	head: string,
	branch: string,
	bare: boolean,
	detached: boolean,
	locked: boolean,
	lockReason: string | null,
	prunable: boolean,
	main: boolean,
};

export type WorktreeOperation = { type: "create"; branch: string; new_branch: boolean } | { type: "remove"; path: string; force: boolean } | { type: "lock"; path: string } | { type: "unlock"; path: string } | { type: "prune" };
