// This file is generated by Rust. Do not edit.

// This file has been generated by Specta. Do not edit this file manually.
export type AppStateSnapshot = {
	schemaVersion?: number,
	settings?: DesktopSettings,
	layout?: LayoutState,
	lastWorkspaceId: string | null,
	openWorkspaceIds?: string[],
	activeWorkspaceId?: string | null,
	recentWorkspaces: WorkspaceDescriptor[],
	theme?: ThemePreference | null,
	language?: LanguagePreference | null,
	uiFontSize?: UiFontSizePreference | null,
	panelSizes?: PanelSizes | null,
	activeTab?: string | null,
	fileViewMode?: string | null,
	stashViewMode?: string | null,
	externalEditor?: ExternalEditor | null,
	branchSidebarCollapsed?: boolean | null,
	branchSidebarCollapsedSections?: string[] | null,
};

export type BatchCommitTarget = {
	repoId: string,
	message: string,
	amend: boolean,
	paths: string[],
};

export type BootstrapData = {
	state: AppStateSnapshot,
	tools: ToolAvailability,
	capabilities: DesktopCapabilities,
};

export type BranchCompareResult = {
	base: string,
	target: string,
	baseCommits: CommitNode[],
	targetCommits: CommitNode[],
	files: CommitFile[],
};

export type BranchInfo = {
	name: string,
	current: boolean,
	remote: boolean,
	remoteName?: string | null,
	upstream: string | null,
	ahead: number,
	behind: number,
	detachedTag?: string | null,
	detachedHash?: string | null,
};

export type BranchOperation = { type: "create"; name: string; from: string | null } | { type: "checkout"; name: string } | { type: "merge"; name: string } | { type: "rebase"; name: string } | { type: "rename"; old_name: string; new_name: string } | { type: "delete"; name: string; force: boolean };

export type BridgeCommand = { type: "bootstrap" } | { type: "saveAppState"; payload: {
	state: AppStateSnapshot,
} } | { type: "updateSettings"; payload: {
	settings: DesktopSettings,
} } | { type: "updateLayout"; payload: {
	layout: LayoutState,
} } | { type: "workspaceOpen"; payload: {
	paths: string[],
} } | { type: "workspaceRemoveRecent"; payload: {
	workspace_id: string,
} } | { type: "workspaceRefresh"; payload: {
	workspace_id: string,
} } | { type: "windowOpenNew"; payload: {
	paths: string[] | null,
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
} } | { type: "windowSyncTabs"; payload: {
	window_label: string,
	workspace_paths: string[][],
} } | { type: "windowFocusWorkspace"; payload: {
	current_window_label: string,
	paths: string[],
} } | { type: "repositoryStatus"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "fileDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	staged: boolean,
	revision: string | null,
	from_revision: string | null,
	to_revision: string | null,
} } | { type: "stashFileDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	reference: string,
	relative_path: string,
} } | { type: "shelfFileDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	shelf_id: string,
	relative_path: string,
} } | { type: "stage"; payload: {
	workspace_id: string,
	repo_id: string,
	paths: string[],
} } | { type: "unstage"; payload: {
	workspace_id: string,
	repo_id: string,
	paths: string[],
} } | { type: "discard"; payload: {
	workspace_id: string,
	repo_id: string,
	paths: string[],
} } | { type: "deletePaths"; payload: {
	workspace_id: string,
	repo_id: string,
	paths: string[],
} } | { type: "addIgnore"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
} } | { type: "ignoreRules"; payload: {
	workspace_id: string,
	repo_id: string,
	directory: string,
} } | { type: "updateIgnoreRules"; payload: {
	workspace_id: string,
	repo_id: string,
	directory: string,
	patterns: string[],
} } | { type: "commit"; payload: {
	workspace_id: string,
	repo_id: string,
	message: string,
	amend: boolean,
	paths: string[],
} } | { type: "batchCommit"; payload: {
	workspace_id: string,
	targets: BatchCommitTarget[],
	push: boolean,
} } | { type: "sync"; payload: {
	workspace_id: string,
	repo_id: string,
	action: SyncAction,
	remote: string | null,
} } | { type: "history"; payload: {
	workspace_id: string,
	repo_id: string,
	skip: number,
	limit: number,
	filter: string | null,
	revision: string | null,
} } | { type: "historyTopology"; payload: {
	workspace_id: string,
	repo_id: string,
	svn_limit: number,
} } | { type: "commitDetail"; payload: {
	workspace_id: string,
	repo_id: string,
	revision: string,
} } | { type: "commitMergeCommits"; payload: {
	workspace_id: string,
	repo_id: string,
	revision: string,
	parents: string[],
} } | { type: "commitMergeParentFiles"; payload: {
	workspace_id: string,
	repo_id: string,
	revision: string,
	parent_hash: string,
} } | { type: "unpushedCommits"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "unpushedOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: UnpushedOperation,
} } | { type: "historyOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: HistoryOperation,
} } | { type: "createPatch"; payload: {
	workspace_id: string,
	repo_id: string,
	revisions: string[],
} } | { type: "branches"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "branchOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: BranchOperation,
} } | { type: "tags"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "tagOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: TagOperation,
} } | { type: "stashes"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "stashOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: StashOperation,
} } | { type: "systemOpen"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	reveal: boolean,
	external: boolean,
} } | { type: "shelves"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "shelfOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: ShelfOperation,
} } | { type: "changelists"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "changelistOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: ChangelistOperation,
} } | { type: "worktrees"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "worktreeOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: WorktreeOperation,
} } | { type: "openWorktree"; payload: {
	workspace_id: string,
	repo_id: string,
	path: string,
	reveal: boolean,
} } | { type: "worktreeDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	path: string,
	base_ref: string,
} } | { type: "worktreeFileDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	path: string,
	base_ref: string,
	relative_path: string,
} } | { type: "branchWorkingDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	base_ref: string,
} } | { type: "branchWorkingFileDiff"; payload: {
	workspace_id: string,
	repo_id: string,
	base_ref: string,
	relative_path: string,
} } | { type: "subtrees"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "subtreeOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: SubtreeOperation,
} } | { type: "submodules"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "submoduleOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: SubmoduleOperation,
} } | { type: "branchCompare"; payload: {
	workspace_id: string,
	repo_id: string,
	base: string,
	target: string,
} } | { type: "remotes"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "remoteOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: RemoteOperation,
} } | { type: "conflicts"; payload: {
	workspace_id: string,
} } | { type: "conflictVersions"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
} } | { type: "conflictSave"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	content: string,
	expected_fingerprint: string,
} } | { type: "conflictAccept"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	choice: ConflictChoice,
} } | { type: "abortRepositoryOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: string,
} } | { type: "gitIdentity"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "gitProfileOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: GitProfileOperation,
} } | { type: "svnAccount"; payload: {
	workspace_id: string,
	repo_id: string,
} } | { type: "svnAccountOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: SvnAccountOperation,
} } | { type: "svnOperation"; payload: {
	workspace_id: string,
	repo_id: string,
	operation: SvnOperation,
} } | { type: "fileHistory"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	cursor: string | null,
	limit: number,
} } | { type: "fileRevisionContent"; payload: {
	workspace_id: string,
	repo_id: string,
	relative_path: string,
	revision: string,
} };

export type ChangelistEntry = {
	id: string,
	name: string,
	files: string[],
};

export type ChangelistOperation = { type: "create"; name: string } | { type: "rename"; changelist_id: string; name: string } | { type: "delete"; changelist_id: string } | { type: "assign"; changelist_id: string | null; paths: string[] };

export type ChangesDisplayMode = "simplified" | "changelists";

export type CommitBranches = {
	local: string[],
	remote: string[],
	tags: string[],
};

export type CommitDetail = {
	commit: CommitNode,
	fullMessage: string,
	files: CommitFile[],
	branches: CommitBranches,
	mergeParentChanges?: MergeParentChange[],
};

export type CommitFile = {
	path: string,
	status: string,
	added: number | null,
	removed: number | null,
};

export type CommitNode = {
	repoId: string,
	hash: string,
	shortHash: string,
	parents: string[],
	author: string,
	email: string,
	authorDate: string,
	committerDate: string,
	message: string,
	refs: string[],
	incoming?: boolean,
	unpushed?: boolean,
};

export type CommitPathOperationEntry = {
	revision: string,
	path: string,
	status: string,
};

export type ConflictChoice = "mine" | "theirs" | "working";

export type ConflictFile = {
	repoId: string,
	repoName: string,
	repoColor: string,
	path: string,
	kind: VcsKind,
	binary: boolean,
	conflictType?: string,
	actions?: string[],
};

export type DefaultCommitAction = "commit" | "commitAndPush";

export type DefaultSaveAction = "stash" | "shelf";

export type DesktopCapabilities = {
	ai: boolean,
	stash: boolean,
	shelf: boolean,
	changelist: boolean,
	worktree: boolean,
	subtree: boolean,
	submodule?: boolean,
	compare: boolean,
	remoteManagement: boolean,
	identity?: boolean,
	svnAccount?: boolean,
	fileHistory?: boolean,
	secureCredentials?: boolean,
	systemNotifications?: boolean,
};

export type DesktopError = {
	code: string,
	message: string,
	command: string | null,
	exitCode: number | null,
	stderr: string | null,
	recoverable: boolean,
	operation?: string | null,
	workspaceId?: string | null,
	repositoryId?: string | null,
	subject?: string | null,
	hint?: string | null,
};

export type DesktopSettings = {
	theme: ThemePreference,
	language: LanguagePreference,
	uiFontSize: UiFontSizePreference,
	changesDisplayMode: ChangesDisplayMode,
	defaultCommitAction: DefaultCommitAction,
	defaultSaveAction: DefaultSaveAction,
	promptBeforeAddingUntracked: boolean,
	suppressDivergedWarning: boolean,
	autoRefreshInterval: number,
	fetchOnStartup: boolean,
	resetViewLocationsOnStartup: boolean,
	notifyIncomingCommits: boolean,
	notifyUnpushedCommits: boolean,
	repositoryScanDepth: number,
	ignoredFolders: string[],
	maximumGraphCommits: number,
	projectColors: { [key in string]: string },
	hiddenRepositoryIds?: string[],
	externalEditor: ExternalEditor | null,
};

export type DiffDocument = {
	path: string,
	content: string,
	language: string,
	binary: boolean,
	truncated: boolean,
	lineCount: number,
};

export type EffectiveGitIdentity = {
	userName: string,
	email: string,
	source: GitIdentitySource,
	profileId: string | null,
	valid: boolean,
};

export type ExternalEditor = {
	executable: string,
	args: string[],
};

export type FileChange = {
	path: string,
	status: string,
	staged: boolean,
	unstaged: boolean,
	conflicted: boolean,
	conflictType?: string | null,
	submodule?: boolean,
};

export type FileHistoryEntry = {
	revision: string,
	previousRevision: string | null,
	path: string,
	previousPath: string | null,
	author: string,
	date: string,
	message: string,
	status: string,
};

export type FileHistoryPage = {
	entries: FileHistoryEntry[],
	nextCursor: string | null,
};

export type FileRevisionDocument = {
	revision: string,
	path: string,
	content: string,
	binary: boolean,
	truncated: boolean,
};

export type GitIdentitySource = "custom" | "local" | "global" | "missing";

export type GitIdentityState = {
	profiles: GitProfile[],
	selectedProfileId: string | null,
	local: EffectiveGitIdentity | null,
	global: EffectiveGitIdentity | null,
	effective: EffectiveGitIdentity,
};

export type GitProfile = {
	id: string,
	label: string,
	userName: string,
	email: string,
};

export type GitProfileOperation = { type: "save"; profile: GitProfile } | { type: "delete"; profile_id: string } | { type: "select"; profile_id: string | null };

export type GraphCommitNode = {
	repoId: string,
	hash: string,
	parents: string[],
	committerDate: string,
	refs: string[],
};

export type HistoryOperation = { type: "checkout"; revision: string } | { type: "cherryPick"; revision: string } | { type: "revert"; revisions: string[] } | { type: "reset"; revision: string; mode: string } | { type: "checkoutFile"; revision: string; path: string } | { type: "revertFile"; revision: string; path: string } | { type: "applyPaths"; entries: CommitPathOperationEntry[] } | { type: "revertPaths"; entries: CommitPathOperationEntry[] } | { type: "svnUpdateTo"; revision: string };

export type HistoryPage = {
	commits: CommitNode[],
	hasMore: boolean,
};

export type IgnoreRules = {
	directory: string,
	source: string,
	patterns: string[],
};

export type LanguagePreference = "system" | "zhCn" | "en";

export type LayoutState = {
	panelSizes: PanelSizes,
	activeTab: string,
	fileViewMode: string,
	stashViewMode: string,
	branchSidebarCollapsed: boolean,
	branchSidebarCollapsedSections: string[],
};

export type MergeCommitSummary = {
	hash: string,
	shortHash: string,
	message: string,
	author: string,
	authorDate: string,
	parentIndex: number,
};

export type MergeParentChange = {
	hash: string,
	shortHash: string,
	message: string,
	authorName: string,
	authorDate: string,
	parentIndex: number,
	fileCount: number,
};

export type MergeVersions = {
	path: string,
	base: string,
	ours: string,
	theirs: string,
	working: string,
	language: string,
	fingerprint: string,
	binary: boolean,
};

export type PanelSizes = {
	commit: number,
	branches: number,
	detail: number,
};

export type PatchDocument = {
	fileName: string,
	content: string,
};

export type ProgressEvent = {
	requestId: string,
	phase: string,
	message: string,
	completed: number | null,
	total: number | null,
};

export type RemoteInfo = {
	name: string,
	fetchUrl: string,
	pushUrl: string,
};

export type RemoteOperation = { type: "add"; name: string; url: string } | { type: "rename"; old_name: string; new_name: string } | { type: "setUrl"; name: string; url: string; push: boolean } | { type: "remove"; name: string } | { type: "prune"; name: string };

export type RepositoryCapabilities = {
	status: boolean,
	diff: boolean,
	commit: boolean,
	sync: boolean,
	history: boolean,
	conflict: boolean,
	stash: boolean,
	shelf: boolean,
	changelist: boolean,
	worktree: boolean,
	subtree: boolean,
	submodule: boolean,
	compare: boolean,
	remoteManagement: boolean,
	identity: boolean,
	svnAccount: boolean,
	fileHistory: boolean,
};

export type RepositoryEvent = {
	workspaceId: string,
	repoId: string,
	generation: number,
	reason: string,
};

export type RepositoryMeta = {
	id: string,
	name: string,
	rootPath: string,
	color: string,
	kind: VcsKind,
	parentRepoId: string | null,
	depth: number,
	isSubmodule: boolean,
	isWorktree: boolean,
};

export type RepositoryOperationResult = {
	repoId: string,
	committed: boolean,
	revision: string | null,
	pushed: boolean,
	error: DesktopError | null,
};

export type RepositoryStatus = {
	meta: RepositoryMeta,
	branch: string,
	revision: string,
	ahead: number,
	behind: number,
	files: FileChange[],
	conflicts: number,
	operation: string | null,
	capabilities?: RepositoryCapabilities,
	toolAvailable?: boolean,
};

export type RequestEnvelope = {
	requestId: string,
	command: BridgeCommand,
};

export type ResponseEnvelope = {
	requestId: string,
	result: unknown,
	error: DesktopError | null,
};

export type SettingsEffects = {
	rescanWorkspace: boolean,
	reloadHistory: boolean,
	restartAutoRefresh: boolean,
};

export type SettingsUpdateResult = {
	settings: DesktopSettings,
	effects: SettingsEffects,
};

export type ShelfEntry = {
	id: string,
	name: string,
	createdAt: string,
	branch?: string | null,
	files: ShelfFileEntry[],
};

export type ShelfFileEntry = {
	path: string,
	status: string,
};

export type ShelfOperation = { type: "create"; name: string; paths: string[] } | { type: "apply"; shelf_id: string; paths?: string[] | null } | { type: "drop"; shelf_id: string };

export type StashEntry = {
	reference: string,
	hash: string,
	branch: string,
	message: string,
	fullMessage: string,
	date: string,
	files: ShelfFileEntry[],
};

export type StashOperation = { type: "create"; message: string; paths: string[]; include_untracked: boolean } | { type: "apply"; reference: string } | { type: "pop"; reference: string } | { type: "drop"; reference: string };

export type SubmoduleEntry = {
	path: string,
	url: string,
	initialized: boolean,
	revision: string | null,
	branch: string | null,
	dirty: boolean,
};

export type SubmoduleOperation = { type: "init"; path: string; recursive: boolean } | { type: "update"; path: string; init: boolean; recursive: boolean; remote: boolean } | { type: "deinit"; path: string; force: boolean } | { type: "sync"; path: string; recursive: boolean };

export type SubtreeEntry = {
	id: string,
	prefix: string,
	remote: string,
	branch: string,
	squash: boolean,
	state: SubtreeState,
};

export type SubtreeOperation = { type: "add"; prefix: string; remote: string; branch: string; squash: boolean } | { type: "pull"; subtree_id: string } | { type: "push"; subtree_id: string } | { type: "register"; prefix: string; remote: string; branch: string; squash: boolean } | { type: "edit"; subtree_id: string; prefix: string; remote: string; branch: string; squash: boolean } | { type: "deleteRegistry"; subtree_id: string } | { type: "removeFiles"; subtree_id: string } | { type: "split"; subtree_id: string; branch: string | null } | { type: "merge"; subtree_id: string; revision: string; squash: boolean; message: string | null };

export type SubtreeState = "active" | "pending";

export type SvnAccountOperation = { type: "save"; username: string; password: string | null } | { type: "delete" } | { type: "test" };

export type SvnAccountState = {
	repositoryRoot: string,
	username: string | null,
	passwordStored: boolean,
	secureStorageAvailable: boolean,
	passwordStdinSupported: boolean,
	connectionOk: boolean | null,
};

export type SvnOperation = { type: "cleanup"; break_locks: boolean; remove_unversioned: boolean; remove_ignored: boolean; include_externals: boolean } | { type: "resolveWorking"; paths: string[] } | { type: "lock"; paths: string[]; message: string | null; force: boolean } | { type: "unlock"; paths: string[]; force: boolean } | { type: "relocate"; from_url: string; to_url: string } | { type: "switch"; url: string; revision: string | null; ignore_ancestry: boolean } | { type: "copy"; source_url: string; destination_url: string; revision: string | null; message: string };

export type SyncAction = "fetch" | "pull" | "push" | "update";

export type TagInfo = {
	name: string,
	hash: string,
	date: string,
};

export type TagOperation = { type: "create"; name: string; revision: string | null } | { type: "delete"; name: string } | { type: "checkout"; name: string } | { type: "merge"; name: string } | { type: "push"; name: string; remote: string };

export type ThemePreference = "system" | "light" | "dark";

export type ToolAvailability = {
	git: boolean,
	svn: boolean,
	svnadmin: boolean,
};

export type UiFontSizePreference = "minimum" | "small" | "standard" | "large" | "maximum";

export type UnpushedCommit = {
	hash: string,
	shortHash: string,
	message: string,
	author: string,
	date: string,
	filesChanged: number,
	additions: number,
	deletions: number,
};

export type UnpushedOperation = { type: "revert"; hashes: string[] } | { type: "undoHead" } | { type: "drop"; hashes: string[] } | { type: "squash"; hashes: string[]; message: string } | { type: "editMessage"; hash: string; message: string };

export type VcsKind = "git" | "svn";

export type WorkspaceDescriptor = {
	id: string,
	name: string,
	paths: string[],
	lastOpenedAt: string,
	available: boolean,
};

export type WorkspaceEvent = {
	workspaceId: string,
	generation: number,
	reason: string,
};

export type WorkspaceSnapshot = {
	workspace: WorkspaceDescriptor,
	repositories: RepositoryStatus[],
	generation: number,
	tools: ToolAvailability,
};

export type WorktreeDiffResult = {
	path: string,
	baseRef: string,
	currentRef: string,
	files: CommitFile[],
};

export type WorktreeEntry = {
	path: string,
	head: string,
	branch: string,
	bare: boolean,
	detached: boolean,
	locked: boolean,
	lockReason: string | null,
	prunable: boolean,
	main: boolean,
};

export type WorktreeOperation = { type: "create"; branch: string; new_branch: boolean } | { type: "remove"; path: string; force: boolean } | { type: "lock"; path: string } | { type: "unlock"; path: string } | { type: "prune" };
