import type { ThemeRegistrationRaw } from 'shiki';

const darkTokens = [
  { scope: ['comment', 'punctuation.definition.comment', 'string.comment'], settings: { foreground: '#8b949e' } },
  { scope: ['constant.other.placeholder', 'constant.character'], settings: { foreground: '#ff7b72' } },
  { scope: ['constant', 'entity.name.constant', 'variable.other.constant', 'variable.other.enummember', 'variable.language', 'entity'], settings: { foreground: '#79c0ff' } },
  { scope: ['entity.name', 'meta.export.default', 'meta.definition.variable'], settings: { foreground: '#ffa657' } },
  { scope: ['variable.parameter.function', 'meta.jsx.children', 'meta.block', 'meta.tag.attributes', 'entity.name.constant', 'meta.object.member', 'meta.embedded.expression'], settings: { foreground: '#c9d1d9' } },
  { scope: 'entity.name.function', settings: { foreground: '#d2a8ff' } },
  { scope: ['entity.name.tag', 'support.class.component'], settings: { foreground: '#7ee787' } },
  { scope: 'keyword', settings: { foreground: '#ff7b72' } },
  { scope: ['storage', 'storage.type'], settings: { foreground: '#ff7b72' } },
  { scope: ['storage.modifier.package', 'storage.modifier.import', 'storage.type.java'], settings: { foreground: '#c9d1d9' } },
  { scope: ['string', 'string punctuation.section.embedded source'], settings: { foreground: '#a5d6ff' } },
  { scope: 'support', settings: { foreground: '#79c0ff' } },
  { scope: 'meta.property-name', settings: { foreground: '#79c0ff' } },
  { scope: 'variable', settings: { foreground: '#ffa657' } },
  { scope: 'variable.other', settings: { foreground: '#c9d1d9' } },
  { scope: 'invalid.broken', settings: { foreground: '#ffa198', fontStyle: 'italic' } },
  { scope: 'invalid.deprecated', settings: { foreground: '#ffa198', fontStyle: 'italic' } },
  { scope: 'invalid.illegal', settings: { foreground: '#ffa198', fontStyle: 'italic' } },
  { scope: 'invalid.unimplemented', settings: { foreground: '#ffa198', fontStyle: 'italic' } },
  { scope: 'carriage-return', settings: { foreground: '#f0f6fc', background: '#8b1111', fontStyle: 'italic underline' } },
  { scope: 'message.error', settings: { foreground: '#ffa198' } },
  { scope: 'string variable', settings: { foreground: '#79c0ff' } },
  { scope: ['source.regexp', 'string.regexp'], settings: { foreground: '#a5d6ff' } },
  { scope: ['string.regexp.character-class', 'string.regexp constant.character.escape', 'string.regexp source.ruby.embedded', 'string.regexp string.regexp.arbitrary-repitition'], settings: { foreground: '#a5d6ff' } },
  { scope: 'string.regexp constant.character.escape', settings: { foreground: '#7ee787', fontStyle: 'bold' } },
  { scope: 'support.constant', settings: { foreground: '#79c0ff' } },
  { scope: 'support.variable', settings: { foreground: '#79c0ff' } },
  { scope: 'support.type.property-name.json', settings: { foreground: '#7ee787' } },
  { scope: 'meta.module-reference', settings: { foreground: '#79c0ff' } },
  { scope: 'punctuation.definition.list.begin.markdown', settings: { foreground: '#ffa657' } },
  { scope: ['markup.heading', 'markup.heading entity.name'], settings: { foreground: '#79c0ff', fontStyle: 'bold' } },
  { scope: 'markup.quote', settings: { foreground: '#7ee787' } },
  { scope: 'markup.italic', settings: { foreground: '#c9d1d9', fontStyle: 'italic' } },
  { scope: 'markup.bold', settings: { foreground: '#c9d1d9', fontStyle: 'bold' } },
  { scope: ['markup.underline'], settings: { fontStyle: 'underline' } },
  { scope: ['markup.strikethrough'], settings: { fontStyle: 'strikethrough' } },
  { scope: 'markup.inline.raw', settings: { foreground: '#79c0ff' } },
  { scope: ['markup.deleted', 'meta.diff.header.from-file', 'punctuation.definition.deleted'], settings: { foreground: '#ffa198', background: '#490202' } },
  { scope: ['punctuation.section.embedded'], settings: { foreground: '#ff7b72' } },
  { scope: ['markup.inserted', 'meta.diff.header.to-file', 'punctuation.definition.inserted'], settings: { foreground: '#7ee787', background: '#04260f' } },
  { scope: ['markup.changed', 'punctuation.definition.changed'], settings: { foreground: '#ffa657', background: '#5a1e02' } },
  { scope: ['markup.ignored', 'markup.untracked'], settings: { foreground: '#0d1117', background: '#79c0ff' } },
  { scope: 'meta.diff.range', settings: { foreground: '#d2a8ff', fontStyle: 'bold' } },
  { scope: 'meta.diff.header', settings: { foreground: '#79c0ff' } },
  { scope: 'meta.separator', settings: { foreground: '#79c0ff', fontStyle: 'bold' } },
  { scope: 'meta.output', settings: { foreground: '#79c0ff' } },
  { scope: ['brackethighlighter.tag', 'brackethighlighter.curly', 'brackethighlighter.round', 'brackethighlighter.square', 'brackethighlighter.angle', 'brackethighlighter.quote'], settings: { foreground: '#8b949e' } },
  { scope: 'brackethighlighter.unmatched', settings: { foreground: '#ffa198' } },
  { scope: ['constant.other.reference.link', 'string.other.link'], settings: { foreground: '#a5d6ff' } },
  { scope: 'token.info-token', settings: { foreground: '#6796E6' } },
  { scope: 'token.warn-token', settings: { foreground: '#CD9731' } },
  { scope: 'token.error-token', settings: { foreground: '#F44747' } },
  { scope: 'token.debug-token', settings: { foreground: '#B267E6' } },
];

export const theme2026Dark: ThemeRegistrationRaw = {
  name: '2026-dark',
  type: 'dark',
  colors: {
    'editor.background': '#121314',
    'editor.foreground': '#BBBEBF',
    'editorLineNumber.foreground': '#858889',
    'editorLineNumber.activeForeground': '#BBBEBF',
    'editorCursor.foreground': '#BBBEBF',
    'editor.selectionBackground': '#276782dd',
    'editor.inactiveSelectionBackground': '#27678260',
    'editor.selectionHighlightBackground': '#27678260',
    'editor.wordHighlightBackground': '#27678250',
    'editor.wordHighlightStrongBackground': '#27678280',
    'editor.findMatchBackground': '#27678290',
    'editor.findMatchHighlightBackground': '#27678280',
    'editor.findRangeHighlightBackground': '#242526',
    'editor.hoverHighlightBackground': '#242526',
    'editor.lineHighlightBackground': '#242526',
    'editor.rangeHighlightBackground': '#242526',
    'editorLink.activeForeground': '#3a94bc',
    'editorWhitespace.foreground': '#8C8C8C4D',
    'editorIndentGuide.background': '#8384854D',
    'editorIndentGuide.activeBackground': '#838485',
    'editorRuler.foreground': '#848484',
    'editorCodeLens.foreground': '#8C8C8C',
    'editorBracketMatch.background': '#3994BC55',
    'editorBracketMatch.border': '#2A2B2CFF',
  },
  settings: darkTokens,
  tokenColors: darkTokens,
};

const lightTokens = [
  { scope: ['comment', 'punctuation.definition.comment', 'string.comment'], settings: { foreground: '#6e7781' } },
  { scope: ['constant.other.placeholder', 'constant.character'], settings: { foreground: '#cf222e' } },
  { scope: ['constant', 'entity.name.constant', 'variable.other.constant', 'variable.other.enummember', 'variable.language', 'entity'], settings: { foreground: '#0550ae' } },
  { scope: ['entity.name', 'meta.export.default', 'meta.definition.variable'], settings: { foreground: '#953800' } },
  { scope: ['variable.parameter.function', 'meta.jsx.children', 'meta.block', 'meta.tag.attributes', 'entity.name.constant', 'meta.object.member', 'meta.embedded.expression'], settings: { foreground: '#1f2328' } },
  { scope: 'entity.name.function', settings: { foreground: '#8250df' } },
  { scope: ['entity.name.tag', 'support.class.component'], settings: { foreground: '#116329' } },
  { scope: 'keyword', settings: { foreground: '#cf222e' } },
  { scope: ['storage', 'storage.type'], settings: { foreground: '#cf222e' } },
  { scope: ['storage.modifier.package', 'storage.modifier.import', 'storage.type.java'], settings: { foreground: '#1f2328' } },
  { scope: ['string', 'string punctuation.section.embedded source'], settings: { foreground: '#0a3069' } },
  { scope: 'support', settings: { foreground: '#0550ae' } },
  { scope: 'meta.property-name', settings: { foreground: '#0550ae' } },
  { scope: 'variable', settings: { foreground: '#953800' } },
  { scope: 'variable.other', settings: { foreground: '#1f2328' } },
  { scope: 'invalid.broken', settings: { fontStyle: 'italic', foreground: '#82071e' } },
  { scope: 'invalid.deprecated', settings: { fontStyle: 'italic', foreground: '#82071e' } },
  { scope: 'invalid.illegal', settings: { fontStyle: 'italic', foreground: '#82071e' } },
  { scope: 'invalid.unimplemented', settings: { fontStyle: 'italic', foreground: '#82071e' } },
  { scope: 'carriage-return', settings: { fontStyle: 'italic underline', background: '#cf222e', foreground: '#f6f8fa' } },
  { scope: 'message.error', settings: { foreground: '#82071e' } },
  { scope: 'string variable', settings: { foreground: '#0550ae' } },
  { scope: ['source.regexp', 'string.regexp'], settings: { foreground: '#0a3069' } },
  { scope: ['string.regexp.character-class', 'string.regexp constant.character.escape', 'string.regexp source.ruby.embedded', 'string.regexp string.regexp.arbitrary-repitition'], settings: { foreground: '#0a3069' } },
  { scope: 'string.regexp constant.character.escape', settings: { fontStyle: 'bold', foreground: '#116329' } },
  { scope: 'support.constant', settings: { foreground: '#0550ae' } },
  { scope: 'support.variable', settings: { foreground: '#0550ae' } },
  { scope: 'support.type.property-name.json', settings: { foreground: '#116329' } },
  { scope: 'meta.module-reference', settings: { foreground: '#0550ae' } },
  { scope: 'punctuation.definition.list.begin.markdown', settings: { foreground: '#953800' } },
  { scope: ['markup.heading', 'markup.heading entity.name'], settings: { fontStyle: 'bold', foreground: '#0550ae' } },
  { scope: 'markup.quote', settings: { foreground: '#116329' } },
  { scope: 'markup.italic', settings: { fontStyle: 'italic', foreground: '#1f2328' } },
  { scope: 'markup.bold', settings: { fontStyle: 'bold', foreground: '#1f2328' } },
  { scope: ['markup.underline'], settings: { fontStyle: 'underline' } },
  { scope: ['markup.strikethrough'], settings: { fontStyle: 'strikethrough' } },
  { scope: 'markup.inline.raw', settings: { foreground: '#0550ae' } },
  { scope: ['markup.deleted', 'meta.diff.header.from-file', 'punctuation.definition.deleted'], settings: { background: '#ffebe9', foreground: '#82071e' } },
  { scope: ['punctuation.section.embedded'], settings: { foreground: '#cf222e' } },
  { scope: ['markup.inserted', 'meta.diff.header.to-file', 'punctuation.definition.inserted'], settings: { background: '#dafbe1', foreground: '#116329' } },
  { scope: ['markup.changed', 'punctuation.definition.changed'], settings: { background: '#ffd8b5', foreground: '#953800' } },
  { scope: ['markup.ignored', 'markup.untracked'], settings: { foreground: '#eaeef2', background: '#0550ae' } },
  { scope: 'meta.diff.range', settings: { foreground: '#8250df', fontStyle: 'bold' } },
  { scope: 'meta.diff.header', settings: { foreground: '#0550ae' } },
  { scope: 'meta.separator', settings: { fontStyle: 'bold', foreground: '#0550ae' } },
  { scope: 'meta.output', settings: { foreground: '#0550ae' } },
  { scope: ['brackethighlighter.tag', 'brackethighlighter.curly', 'brackethighlighter.round', 'brackethighlighter.square', 'brackethighlighter.angle', 'brackethighlighter.quote'], settings: { foreground: '#57606a' } },
  { scope: 'brackethighlighter.unmatched', settings: { foreground: '#82071e' } },
  { scope: ['constant.other.reference.link', 'string.other.link'], settings: { foreground: '#0a3069' } },
];

export const theme2026Light: ThemeRegistrationRaw = {
  name: '2026-light',
  type: 'light',
  colors: {
    'editor.background': '#FFFFFF',
    'editor.foreground': '#202020',
    'editorLineNumber.foreground': '#606060',
    'editorLineNumber.activeForeground': '#202020',
    'editorCursor.foreground': '#202020',
    'editor.selectionBackground': '#0069CC40',
    'editor.inactiveSelectionBackground': '#0069CC1A',
    'editor.selectionHighlightBackground': '#0069CC15',
    'editor.wordHighlightBackground': '#0069CC26',
    'editor.wordHighlightStrongBackground': '#0069CC26',
    'editor.findMatchBackground': '#0069CC40',
    'editor.findMatchHighlightBackground': '#0069CC1A',
    'editor.findRangeHighlightBackground': '#EAEAEA',
    'editor.hoverHighlightBackground': '#EAEAEA',
    'editor.lineHighlightBackground': '#EAEAEA40',
    'editor.rangeHighlightBackground': '#EAEAEA',
    'editorLink.activeForeground': '#0069CC',
    'editorWhitespace.foreground': '#60606040',
    'editorIndentGuide.background': '#F7F7F740',
    'editorIndentGuide.activeBackground': '#EEEEEE',
    'editorRuler.foreground': '#F7F7F7',
    'editorCodeLens.foreground': '#606060',
    'editorBracketMatch.background': '#0069CC40',
    'editorBracketMatch.border': '#F0F1F2FF',
  },
  settings: lightTokens,
  tokenColors: lightTokens,
};

export function resolveShikiTheme(effectiveTheme?: string | null): ThemeRegistrationRaw | 'dark-plus' | 'light-plus' | 'github-dark-dimmed' | 'one-dark-pro' | 'dracula' | 'nord' {
  if (effectiveTheme === 'light') return 'light-plus';
  if (effectiveTheme === 'dark') return 'dark-plus';
  if (effectiveTheme === 'githubDarkDimmed') return 'github-dark-dimmed';
  if (effectiveTheme === 'oneDarkPro') return 'one-dark-pro';
  if (effectiveTheme === 'dracula') return 'dracula';
  if (effectiveTheme === 'nord') return 'nord';
  if (effectiveTheme === 'light2026') return theme2026Light;
  return theme2026Dark;
}
