import { useCallback, useEffect, useRef, useState } from 'react';
import { openUrl } from '@tauri-apps/plugin-opener';
import type { GithubDeviceFlow, PublishRepositoryResult, RemoteNamespace, RemoteProviderAccount, RemoteRepository, RemoteRepositoryPage, RemoteVisibility } from '../bindings/generated';
import { useBridge } from '../platform/context';
import { useI18n } from '../i18n';
import { Codicon } from './Codicon';
import { useDialogFocusTrap } from '../hooks/useDialogFocusTrap';
import { useAppStore } from '../store/appStore';

export function ProviderPanel({ mode, repoId, close, onClone }: { mode: 'manage' | 'browse' | 'publish'; repoId?: string; close: () => void; onClone?: (repository: RemoteRepository, accountId: string) => void }) {
  const bridge = useBridge(); const { t } = useI18n();
  const workspaceId = useAppStore((state) => state.snapshot?.workspace.id ?? '');
  const providerAvailability = useAppStore((state) => state.bootstrap?.capabilities.availability);
  const authController = useRef<AbortController>();
  useEffect(() => () => authController.current?.abort(), []);
  const [accounts, setAccounts] = useState<RemoteProviderAccount[]>([]); const [selected, setSelected] = useState('');
  const [repositories, setRepositories] = useState<RemoteRepository[]>([]); const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [hasMore, setHasMore] = useState(false);
  const [gitlab, setGitlab] = useState(false); const [host, setHost] = useState('https://gitlab.com'); const [pat, setPat] = useState('');
  const [flow, setFlow] = useState<GithubDeviceFlow>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [editingAccountId, setEditingAccountId] = useState<string>();
  const [namespaces, setNamespaces] = useState<RemoteNamespace[]>([]); const [namespace, setNamespace] = useState(''); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [visibility, setVisibility] = useState<RemoteVisibility>('private'); const [push, setPush] = useState(true); const [publishResult, setPublishResult] = useState<PublishRepositoryResult>();
  const selectedProvider = accounts.find((account) => account.id === selected)?.provider;
  useEffect(() => { if (selectedProvider === 'github' && visibility === 'internal') queueMicrotask(() => setVisibility('private')); }, [selectedProvider, visibility]);
  const dialog = useDialogFocusTrap(true, close);
  const loadAccounts = useCallback(async () => { const values = await bridge.request<RemoteProviderAccount[]>({ type: 'providerAccounts' }, { showProgress: false }); setAccounts(values); setSelected((current) => current || values[0]?.id || ''); }, [bridge]);
  useEffect(() => { queueMicrotask(() => void loadAccounts()); }, [loadAccounts]);
  const loadRepositories = useCallback(async (nextPage = 1, append = false) => { if (!selected) return; setBusy(true); try { const value = await bridge.request<RemoteRepositoryPage>({ type: 'providerRepositories', payload: { account_id: selected, query: query.trim() || null, page: nextPage, per_page: 50 } }, { showProgress: false }); setRepositories((current) => append ? [...current, ...value.items] : value.items); setPage(value.page); setHasMore(value.hasMore); } catch (reason) { setError(String(reason)); } finally { setBusy(false); } }, [bridge, query, selected]);
  useEffect(() => { if (mode === 'browse' && selected) queueMicrotask(() => void loadRepositories()); }, [loadRepositories, mode, selected]);
  useEffect(() => { if (mode !== 'publish' || !selected) return; void bridge.request<RemoteNamespace[]>({ type: 'providerNamespaces', payload: { account_id: selected } }, { showProgress: false }).then((values) => { setNamespaces(values); const github = accounts.find((a) => a.id === selected)?.provider === 'github'; setNamespace(github ? values[0]?.fullPath ?? '' : values[0]?.id ?? ''); }).catch((reason) => setError(String(reason))); }, [accounts, bridge, mode, selected]);
  const beginGithub = async (accountId?: string) => { authController.current?.abort(); const controller = new AbortController(); authController.current = controller; setBusy(true); setError(''); try { const value = await bridge.request<GithubDeviceFlow>({ type: 'providerGithubBegin', payload: { account_id: accountId ?? null } }, { signal: controller.signal }); setFlow(value); await openUrl(value.verificationUri); const account = await bridge.request<RemoteProviderAccount>({ type: 'providerGithubComplete', payload: { flow_id: value.flowId } }, { timeoutMs: 900_000, signal: controller.signal }); await loadAccounts(); setSelected(account.id); setFlow(undefined); } catch (reason) { if (!controller.signal.aborted) setError(String(reason)); } finally { if (!controller.signal.aborted) setBusy(false); } };
  const saveGitlab = async () => { setBusy(true); setError(''); try { const account = await bridge.request<RemoteProviderAccount>({ type: 'providerGitlabSave', payload: { account_id: editingAccountId ?? null, host, token: pat } }); setPat(''); setGitlab(false); setEditingAccountId(undefined); await loadAccounts(); setSelected(account.id); } catch (reason) { setError(String(reason)); } finally { setBusy(false); } };
  const remove = async (id: string) => { await bridge.request({ type: 'providerRemove', payload: { account_id: id } }); await loadAccounts(); };
  const publish = async () => { if (!workspaceId || !repoId || !selected || !name.trim()) return; setBusy(true); setError(''); try { const value = await bridge.request<PublishRepositoryResult>({ type: 'publishRepository', payload: { workspace_id: workspaceId, repo_id: repoId, account_id: selected, namespace_id: namespace || null, name: name.trim(), description: description.trim(), visibility, push } }, { timeoutMs: 600_000 }); setPublishResult(value); } catch (reason) { setError(String(reason)); } finally { setBusy(false); } };
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><section ref={dialog} className="modal-panel provider-panel" role="dialog" aria-modal="true" aria-label={t('Remote Providers')}>
    <header className="modal-header"><div className="modal-header-title"><Codicon name="cloud" /><strong>{t(mode === 'browse' ? 'Browse Remote Repositories' : mode === 'publish' ? 'Publish Repository' : 'Remote Providers')}</strong></div><button onClick={close}><Codicon name="close" /></button></header>
    <div className="provider-body"><aside className="provider-accounts"><button className="primary" title={providerAvailability?.githubProvider?.detail ?? undefined} disabled={busy || providerAvailability?.githubProvider?.available === false} onClick={() => void beginGithub()}><Codicon name="github" />{t('Add GitHub Account')}</button><button title={providerAvailability?.gitlabProvider?.detail ?? undefined} disabled={busy || providerAvailability?.gitlabProvider?.available === false} onClick={() => { setEditingAccountId(undefined); setGitlab(true); }}><Codicon name="key" />{t('Add GitLab Account')}</button>{accounts.map((account) => <div key={account.id} className={selected === account.id ? 'selected' : ''}><button onClick={() => setSelected(account.id)}><strong>{account.provider === 'github' ? 'GitHub' : 'GitLab'}</strong><span>{account.login}</span><small>{account.host}</small></button>{mode === 'manage' && <><button title={t('Reauthenticate')} onClick={() => { if (account.provider === 'github') void beginGithub(account.id); else { setEditingAccountId(account.id); setHost(account.host); setGitlab(true); } }}><Codicon name="refresh" /></button><button title={t('Remove')} onClick={() => void remove(account.id)}><Codicon name="trash" /></button></>}</div>)}</aside>
      <main className="provider-content">{gitlab && <div className="provider-form"><label>{t('GitLab Host')}<input value={host} onChange={(e) => setHost(e.target.value)} /></label><label>{t('Personal Access Token')}<input type="password" value={pat} onChange={(e) => setPat(e.target.value)} /></label><button className="primary" disabled={!pat.trim() || busy} onClick={() => void saveGitlab()}>{t('Connect')}</button></div>}
      {flow && <div className="provider-device"><strong>{flow.userCode}</strong><span>{t('Enter this code in the opened GitHub page.')}</span></div>}
      {mode === 'manage' && !gitlab && <div className="empty-state"><Codicon name="account" />{t('Add or remove remote provider accounts.')}</div>}
      {mode === 'browse' && <><div className="provider-search"><input value={query} placeholder={t('Search repositories…')} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') void loadRepositories(); }} /><button onClick={() => void loadRepositories()}><Codicon name="search" /></button></div><div className="provider-repositories">{repositories.map((repo) => <button key={`${repo.host}:${repo.id}`} onClick={() => onClone?.(repo, selected)}><Codicon name={repo.private ? 'lock' : 'repo'} /><span><strong>{repo.fullName}</strong><small>{repo.defaultBranch ?? t('No default branch')}</small></span></button>)}</div>{hasMore && <button disabled={busy} onClick={() => void loadRepositories(page + 1, true)}>{t('Load more')}</button>}</>}
      {mode === 'publish' && <div className="provider-form"><label>{t('Namespace')}<select value={namespace} onChange={(e) => setNamespace(e.target.value)}>{namespaces.map((item) => <option key={item.id} value={selectedProvider === 'github' ? item.fullPath : item.id}>{item.fullPath}</option>)}</select></label><label>{t('Repository name')}<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>{t('Description')}<textarea value={description} onChange={(e) => setDescription(e.target.value)} /></label><label>{t('Visibility')}<select value={visibility} onChange={(e) => setVisibility(e.target.value as RemoteVisibility)}><option value="private">{t('Private')}</option>{selectedProvider === 'gitlab' && <option value="internal">{t('Internal')}</option>}<option value="public">{t('Public')}</option></select></label><label className="dialog-check"><input type="checkbox" checked={push} onChange={(e) => setPush(e.target.checked)} />{t('Push after creating')}</label><button className="primary" disabled={busy || !name.trim()} onClick={() => void publish()}>{t('Publish')}</button>{publishResult && <div className={publishResult.error ? 'dialog-error' : 'notice'}>{publishResult.error?.message ?? t('Repository published successfully')}{publishResult.recoveryHint && <small>{publishResult.recoveryHint}</small>}</div>}</div>}
      {error && <p className="dialog-error">{error}</p>}</main></div>
  </section></div>;
}
