#![allow(
    clippy::field_reassign_with_default,
    clippy::large_enum_variant,
    clippy::result_large_err
)]

mod changelist;
mod cli;
mod commands;
mod identity;
mod models;
mod shelf;
mod state;
mod svn_account;
mod vcs;
mod workspace;

#[cfg(test)]
mod integration_tests;

use state::AppState;
use tauri::Manager;
use tauri_plugin_window_state::StateFlags;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_system_symbols::init())
        .plugin(tauri_plugin_window_controls::init())
        .plugin(
            tauri_plugin_window_state::Builder::default()
                // The window configuration owns decorations per platform. Do not restore
                // the legacy `decorated: false` value saved by earlier borderless builds.
                .with_state_flags(StateFlags::all() & !StateFlags::DECORATIONS)
                // Detached tab windows have unique labels and should not accumulate stale
                // one-off geometry entries across application runs.
                .with_filter(|label| label == "main")
                .build(),
        )
        .setup(|app| {
            let config_dir = app.path().app_config_dir()?;
            app.manage(AppState::load(config_dir));

            #[cfg(target_os = "windows")]
            {
                use tauri_plugin_window_controls::WindowControlsExt;

                let window = app
                    .get_webview_window("main")
                    .expect("main window not found");
                window.set_title_bar_height(38)?;
                window.set_title_bar_overlay(true)?;
            }

            Ok(())
        })
        .on_window_event(|window, event| {
            if matches!(event, tauri::WindowEvent::Destroyed) {
                let state = window.state::<AppState>();
                let _ = state.unregister_window(window.label());
            }
        })
        .invoke_handler(tauri::generate_handler![
            commands::bridge_request,
            commands::bridge_cancel
        ])
        .run(tauri::generate_context!())
        .expect("error while running VersionDock Desktop");
}

#[cfg(test)]
mod binding_tests {
    use std::path::PathBuf;

    #[test]
    fn export_bindings() {
        let output = specta_typescript::Typescript::default()
            .header("// This file is generated by Rust. Do not edit.\n")
            .export(&specta::collect(), specta_serde::Format)
            .expect("TypeScript bindings should export");
        let target = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/bindings/generated.ts");
        std::fs::create_dir_all(target.parent().expect("binding parent"))
            .expect("binding directory");
        std::fs::write(target, output).expect("write generated bindings");
    }
}
