mod changelist;
mod cli;
mod commands;
mod models;
mod shelf;
mod state;
mod vcs;
mod workspace;

#[cfg(test)]
mod integration_tests;

use state::AppState;
use tauri::Manager;
use tauri_plugin_window_state::StateFlags;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_os::init())
        .plugin(
            tauri_plugin_window_state::Builder::default()
                .with_state_flags(StateFlags::all())
                .build(),
        )
        .setup(|app| {
            let config_dir = app.path().app_config_dir()?;
            app.manage(AppState::load(config_dir));
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            commands::bridge_request,
            commands::bridge_cancel
        ])
        .run(tauri::generate_context!())
        .expect("error while running VersionDock Desktop");
}

#[cfg(test)]
mod binding_tests {
    use std::path::PathBuf;

    #[test]
    fn export_bindings() {
        let output = specta_typescript::Typescript::default()
            .header("// This file is generated by Rust. Do not edit.\n")
            .export(&specta::collect(), specta_serde::Format)
            .expect("TypeScript bindings should export");
        let target = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/bindings/generated.ts");
        std::fs::create_dir_all(target.parent().expect("binding parent"))
            .expect("binding directory");
        std::fs::write(target, output).expect("write generated bindings");
    }
}
